### ISSUE TITLE
Rewrite organization website using NextJS

### ISSUE THREAD

**Issue by WillieCubed** [aisutd/org-site#24]
# Overview
The current AIS website is a single-page application built with React, which isn't well-suited to SEO and is overkill for those not familiar with web frameworks. Content isn't separated from website structure, which makes it cumbersome to generate event links for marketing purposes.

The website is a shell of what it needs to be to support the next chapter in AIS's growth, so it's time for a change.

The website needs to be rewritten to be a primarily static one that can be updated by people without any technical background. We will be using [NextJS](https://nextjs.org/), a framework for building server-side generated and statically-generated sites built with React.

# Proposal
## Routes
The new website will have a few core pages:
- Home (`/`), an overview of the organization with some pretty images
- Events (`/events`), an entrypoint to upcoming and past event information with search functionality
- Demos/Projects (`/demos`), showcasing all the projects produced in AIS by all officers, AIM participants, and members
- Team (`/team`), showing a directory of all the current and past officers of the team
- About (`/about`), showing off the history of the organization
- Join (`'/join`), displaying a link to officer applications and a means of becoming a member of the organization

## Architecture
The website should make very liberal use of fetching data from external sources, like Coda or Google Sheets. **Website content should be updateable without ever having to touch source code.** NextJS makes this easy with its `getStaticProps` functions.

## Branding
The colors, typography, and general aesthetics of the website should reflect the rest of the organization.

**Comment by WillieCubed** [comment]
Uh, what?

**Comment by KumailB** [comment]
Done
